### ISSUE TITLE
No graphics being shown

### ISSUE THREAD

**Issue by rodrigoramos000** [luisfontes19/redmine_stats#3]
Please see attached image. I know it not meant to support 2.4 version, but any clue on how to show the graphics? btw great plugin brazuca! :)

![screenshot_1](https://cloud.githubusercontent.com/assets/10854033/6047452/92c2ba98-ac88-11e4-8b3f-804d025d6322.png)

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.5
  redmine_stats                  0.0.2

**Comment by luisfontes19** [comment]
I am not familiarized with older versions of redmine honestly, but you can have more than 1 problem since the legend colors are not shown too.

First of all check if your browser if compatibly with html5 canvas (needed by the chart.js library, that is the library responsible by creating the charts) http://caniuse.com/#feat=canvas 

Or this could be css related, and would explain the chart and the legend problem...
Check the console error (a simple way to do that is by right-clicking on the page and select the "inspect element" option, or something like that name and you will have a tab named 'Console', that's what you need) for errors related with css (or even js)

**Comment by luisfontes19** [comment]
Closed for inactivity
